version: '3.7'

services:
  reminder:
    build: .
    volumes:
      - ./app/config.json:/app/config.json
      - ./app/sqlite.db:/app/sqlite.db
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
    container_name: scanlation_bot
