name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: 'v1.54'
          args: --timeout=30m
        continue-on-error: true

  security-check:
    needs: lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
        continue-on-error: true

  build:
    needs: security-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y git gcc musl-dev libsqlite3-dev
          go mod download
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o scanlation-discord-bot .
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scanlation-discord-bot
          path: scanlation-discord-bot
